# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

env:
  JWT_SECRET: "f2786b1d4889650a03d2885289db2fb1151efaf2aca507873ba4560ab5082c062aa9e75fbbc9ee32311d6356962f83a5fd439367255913cf4d94a5197a476be0880bcf61f063a36bf31794ba5af4660bc0275b5d2c5664f22d4eda16bbc9fed5296002918a55e9d20e4b2ffcf11c6d0a1a4f8ca730fc6b03c3998f65cee1e10af67bcef14de569d3d2f595634f657f1138501a52ad409632ff098a27a02dfeb93eddfb597a0eef4a9158138488a1aba65d2e5baa535e8a6619a854ae8b65315d05e72322706ac72167f5be5cd3f738505cdd75fe2fa43098a7e731464ebed2df689ef401c5f402aca0092b25957b7b9c6aee51f6d1062b25aad6b4d6e6fdaabb"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['5.0', 6.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install
    - run: npm test
